on: [push]

jobs:
  android_debug_build_job:
    runs-on: ubuntu-latest
    name: debug-build
    env:
      DEBUG_KEYSTORE_BASE64: ${{ secrets.DEBUG_KEYSTORE_BASE64 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: ./.github/actions/android-build
        with:
          command: ./gradlew assembleDebug
      - name: Upload app-debug.apk
        uses: actions/upload-artifact@v1
        with:
          name: APK
          path: app/build/outputs/apk/debug/app-debug.apk
